config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :enrollments

  resources :events
  
  get 'my_enrollments' => 'enrollments#my_enrollments'

   root 'enrollments#index'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :event
  belongs_to :volunteers, class_name: "User"

  YEAR = %w(F.E. S.E. T.E. B.E. Other)

  validates :receipt_no, presence: true, uniqueness: true
  validates :event_name, presence: true
  
  def dept=(value)
    write_attribute(:dept, value.upcase)
  end
  
  def college=(value)
    write_attribute(:college, value.upcase)
  end
  
  def name=(value)
    write_attribute(:name, value.upcase)
  end
  
  def team=(value)
    write_attribute(:team, value.upcase)
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :enrollments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :reg_enrollments, class_name: "Enrollment", foreign_key: "volunteer_id"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_app_events
  
  def set_app_events
    @events = Event.all
  end
  
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :enrollment_owner!, only: [:edit, :update, :destroy]
  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end
  
  def my_enrollments
    vid = current_user.id
    @enrollments = Enrollment.where(:volunteer_id => vid).all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = current_user.reg_enrollments.new(enrollment_params)

    #@enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to new_enrollment_path, notice: 'Enrollment was successfully created.' }
        format.json { render :new, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def enrollment_params
    params.require(:enrollment).permit(:receipt_no, :name, :college, :contact_no, :team, :year, :dept, :amt_paid, :event_name, :volunteer_id, :email)
  end

  def enrollment_owner!
    authenticate_user!
    
    if current_user.id != 1
      if @enrollment.volunteer_id != current_user.id
        redirect_to enrollments_path
        flash[:notice] = 'You do not have enough permissions to do this'
      end
    end
  end #def end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :allow_access, except: [:index]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :index, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :reg_fees, :dept, :coordinator, :contact, :co_coordinator, :co_contact)
    end
    
    def allow_access
      if current_user.id != 1
        redirect_to enrollments_path
      end
    end      
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
<% if @enrollment.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

	<ul>
		<% @enrollment.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :receipt_no %>&nbsp;&nbsp;
	<%= f.text_field :receipt_no, :class=>"rcpt_field", autofocus: true %>

	&nbsp;&nbsp;&nbsp;&nbsp;

	<%= f.label :name %>&nbsp;&nbsp;
	<%= f.text_field :name, :class=>"rcpt_field" %>

	&nbsp;&nbsp;&nbsp;

	<%= f.label :college %>&nbsp;&nbsp;
	<%= f.text_field :college, :class=>"rcpt_field" %>
</div>
<br />

<div class="field">
	<%= f.label :contact_no %>&nbsp;&nbsp;
	<%= f.text_field :contact_no, :class=>"rcpt_field" %>

	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

	<%= f.label :year %>&nbsp;&nbsp;
	<%= f.select :year, Enrollment::YEAR, {}, :class=>"form-control" %>

	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

	<%= f.label :department %>&nbsp;
	<%= f.text_field :dept, :class=>"rcpt_field" %>
</div>
<br />

<div class="field">
	<%= f.label :email %>&nbsp;&nbsp;
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<%= f.text_field :email, :class=>"rcpt_field" %>
</div>

<div class="field">
	<%= f.label :team %>
	<br>
	<%= f.text_area :team, :cols => "70", :rows => "5" %>
</div>
<br />

<div class="field">
	<%= f.label :amt_paid %>&nbsp;&nbsp;
	<%= f.number_field :amt_paid, :class=>"rcpt_field" %>

	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

	<%= f.label :event_name %>&nbsp;&nbsp;
	<%= f.text_field :event_name, :class=>"rcpt_field" %>

</div>
<br />
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1> &nbsp;
<%= link_to 'New Registration', new_enrollment_path, :target => "_blank" %>

<p id="notice"><%= notice %></p>

<table border="0" style="margin-left: 8px; margin-top: 10px" cellpadding="7px" >
  <thead style="font-size: 14px">
    <tr>
      <th>Rcpt no</th>
      <th>Name</th>
      <th>College</th>
      <!-- <th>Contact no</th> -->
      <!-- <th>Email</th> -->
      <th>Team</th>
      <th>Year</th>
      <th>Dept</th>
      <!-- <th>Amt paid</th> -->
      <th>Event name</th>
      <!-- <th>Vol <br /> Id</th> -->
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody style="text-align: center">
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.receipt_no %></td>
        <td style="width: 40px"><%= enrollment.name %></td>
        <td style="width: 45px"><%= enrollment.college %></td>
        <!-- <td><%= enrollment.contact_no %></td> -->
        <!-- <td><%= enrollment.email %></td> -->
        <td style="width: 40px"><%= enrollment.team %></td>
        <td><%= enrollment.year %></td>
        <td><%= enrollment.dept %></td>
        <!-- <td><%= enrollment.amt_paid %></td> -->
        <td><%= enrollment.event_name %></td>
        <!-- <td><%= enrollment.volunteer_id %></td> -->
        
        <!-- <td><%= link_to 'Show', enrollment %></td> -->
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br />

app/views/enrollments/my_enrollments.html.erb
<h1>Listing enrollments</h1>

<p id="notice"><%= notice %></p>

<table border="0" style="margin-left: 10px; margin-top: 10px" cellpadding="8px" >
  <thead style="font-size: 14px">
    <tr>
      <th>Rcpt no</th>
      <th>Name</th>
      <th>College</th>
      <th>Contact no</th>
      <!-- <th>Email</th> -->
      <th>Team</th>
      <!-- <th>Year</th>
      <th>Dept</th> -->
      <th>Amt paid</th>
      <th>Event name</th>
      <th>Vol <br /> Id</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody style="text-align: center">
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.receipt_no %></td>
        <td><%= enrollment.name %></td>
        <td><%= enrollment.college %></td>
        <td><%= enrollment.contact_no %></td>
        <!-- <td><%= enrollment.email %></td> -->
        <td style="width: 50px"><%= enrollment.team %></td>
        <!-- <td><%= enrollment.year %></td>
        <td><%= enrollment.dept %></td> -->
        <td><%= enrollment.amt_paid %></td>
        <td><%= enrollment.event_name %></td>
        <td><%= enrollment.volunteer_id %></td>
        
        <!-- <td><%= link_to 'Show', enrollment %></td> -->
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br />

<%= link_to 'All Registrations', enrollments_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p>
  <strong>Receipt no:</strong>
  <%= @enrollment.receipt_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @enrollment.name %>
</p>

<p>
  <strong>College:</strong>
  <%= @enrollment.college %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @enrollment.contact_no %>
</p>

<p>
  <strong>Team:</strong>
  <%= @enrollment.team %>
</p>

<p>
  <strong>Year:</strong>
  <%= @enrollment.year %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @enrollment.dept %>
</p>

<p>
  <strong>Amt paid:</strong>
  <%= @enrollment.amt_paid %>
</p>

<p>
  <strong>Event name:</strong>
  <%= @enrollment.event_name %>
</p>

<p>
  <strong>Volunteer:</strong>
  <%= @enrollment.volunteer_id %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :reg_fees %><br>
    <%= f.text_field :reg_fees %>
  </div>
  
  <div class="field">
    <%= f.label :dept %><br>
    <%= f.text_field :dept %>
  </div>
  <div class="field">
    <%= f.label :coordinator %><br>
    <%= f.text_field :coordinator %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  
  <div class="field">
    <%= f.label :co_coordinator %><br>
    <%= f.text_field :co_coordinator %>
  </div>
  <div class="field">
    <%= f.label :co_contact %><br>
    <%= f.text_field :co_contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table style="margin-left: 12px; margin-top: 10px" cellpadding="8px">
  <thead style="font-size: 14px">
    <tr>
      <th>Event name</th>
      <th>Reg. Fees</th>
      <th>Dept</th>
      <th>Coordinator</th>
      <th>Contact</th>
      <th>Co-Coordinator</th>
      <th>Co-Contact</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody style="text-align: center">
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.reg_fees %></td>
        <td><%= event.dept %></td>
        <td><%= event.coordinator %></td>
        <td><%= event.contact %></td>
        <td><%= event.co_coordinator %></td>
        <td><%= event.co_contact %></td>
        <!-- <td><%= link_to 'Show', event %></td> -->
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br />

<%= link_to 'New Event', new_event_path %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;

<%= link_to 'View Enrollments', enrollments_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @event.dept %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @event.coordinator %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @event.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @event.email %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Innovation2k15</title>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

	</head>
	<body>

		<div id="header">
			<center>
			<table>
				<tr>
					<td> <%= image_tag "spacer3.gif", :size => "350x10" %> </td>
					<td><h1 style="font-family: monospace; font-size: 30px; color: Indigo" align="center"> Innovation&nbsp;2k15</h1></td>
					<td> <%= image_tag "spacer3.gif", :size => "300x10" %> </td>
					<td>
					<ul class="nav navbar-nav pull-right" style="text-align: right">
						<% if user_signed_in? %>
						<li style="font-size: 14px">
							<a href="/my_enrollments"> <%= "#{current_user.email}" %> </a>
						</li>
						<li class="active" style="font-size: 14px">
							<%= link_to "Logout", destroy_user_session_path, method: :delete %>
						</li>
						<% end %>
					</ul>
					</td>
				</tr>
			</table>
			</center>
		</div>

		<div id="nav">
			<font>
				<div>
					<p style="font-size: 18px">
						<b>Comp</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "Comp" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
				<div>
					<p style="font-size: 18px">
						<b>IT</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "IT" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
				<div>
					<p style="font-size: 18px">
						<b>EnTC</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "EnTC" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
				<div>
					<p style="font-size: 18px">
						<b>Mech</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "Mech" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
				<div>
					<p style="font-size: 18px">
						<b>Instru</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "Instru" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
				<div>
					<p style="font-size: 18px">
						<b>Workshops</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "Workshop" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
				<div>
					<p style="font-size: 18px">
						<b>Common</b>
					</p>
					<% @events.each do |event| %>
					<% if event.dept == "Common" %>
					<button class="evtBtn" value=<%= event.id %> >
						<%= event.event_name %>
					</button>
					<% end %>
					<% end %>
				</div>
		</div>
		</font>
		</div>

		<div id="section">
			<%= yield %>
		</div>

	</body>
</html>